# Generated by Django 4.2.11 on 2025-02-10 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_like_post_like_post_like_user_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_followers',
            field=models.ManyToManyField(to='network.follow'),
        ),
    ]
