# Generated by Django 4.2.11 on 2025-02-12 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_user_user_followers'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('followed', 'following')},
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'post')},
        ),
    ]
