# Generated by Django 4.2.11 on 2025-03-20 00:26

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127)),
                ('address', models.CharField(blank=True, max_length=127)),
                ('email', models.JSONField()),
                ('phone', models.JSONField()),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127)),
                ('Description', models.TextField()),
                ('barcode', models.IntegerField(null=True)),
                ('sku', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127)),
                ('address', models.CharField(blank=True, max_length=127)),
                ('email', models.JSONField()),
                ('phone', models.JSONField()),
                ('notes', models.TextField(blank=True)),
                ('items', models.ManyToManyField(to='exchange.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.JSONField()),
                ('other_costs', models.JSONField()),
                ('amount_on_credit', models.IntegerField()),
                ('notes', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exchange.customer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=31)),
                ('effect_on_date_time', models.DateTimeField(default=datetime.datetime.now)),
                ('expire_on_date_time', models.DateTimeField(null=True)),
                ('notes', models.TextField(blank=True)),
                ('price', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.JSONField()),
                ('other_costs', models.JSONField()),
                ('notes', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exchange.supplier')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NewModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(choices=[('IT', 'Item'), ('SU', 'Supplier'), ('CU', 'Customer'), ('IN', 'inventory'), ('CR', 'credit'), ('PR', 'price'), ('OR', 'order'), ('SA', 'sale')], max_length=2)),
                ('model_id', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=31)),
                ('effect_on_date_time', models.DateTimeField(default=datetime.datetime.now)),
                ('expire_on_date_time', models.DateTimeField(null=True)),
                ('notes', models.TextField(blank=True)),
                ('count', models.IntegerField(default=0)),
                ('inventory_restock_warning', models.IntegerField(null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exchange.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FieldChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=31)),
                ('old', models.CharField(max_length=127)),
                ('new', models.CharField(max_length=127)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EditModelContents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(choices=[('IT', 'Item'), ('SU', 'Supplier'), ('CU', 'Customer'), ('IN', 'inventory'), ('CR', 'credit'), ('PR', 'price'), ('OR', 'order'), ('SA', 'sale')], max_length=2)),
                ('model_id', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('cause', models.CharField(max_length=31)),
                ('fields_changed', models.ManyToManyField(to='exchange.fieldchange')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=31)),
                ('effect_on_date_time', models.DateTimeField(default=datetime.datetime.now)),
                ('expire_on_date_time', models.DateTimeField(null=True)),
                ('notes', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.customer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
