# Generated by Django 4.2.11 on 2025-03-20 00:52

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0002_customer_item_supplier_sale_price_order_newmodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_costs', models.JSONField()),
                ('notes', models.TextField(blank=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('items', models.ManyToManyField(to='exchange.orderitem')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exchange.supplier')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='item',
            old_name='Description',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='editmodelcontents',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='fieldchange',
            name='new',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='fieldchange',
            name='old',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='inventory_restock_warning',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='barcode',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='sku',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='newmodel',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sale',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.RemoveField(
            model_name='sale',
            name='items',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exchange.item'),
        ),
        migrations.AddField(
            model_name='sale',
            name='items',
            field=models.ManyToManyField(to='exchange.orderitem'),
        ),
    ]
