# Generated by Django 4.2.11 on 2025-03-20 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0003_orderitem_purchase_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='items',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='amount_on_credit',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='items',
        ),
        migrations.AlterField(
            model_name='editmodelcontents',
            name='model',
            field=models.CharField(choices=[('IT', 'Item'), ('SU', 'Supplier'), ('CU', 'Customer'), ('IN', 'inventory'), ('CR', 'credit'), ('PR', 'price'), ('PU', 'purchase'), ('SA', 'sale')], max_length=2),
        ),
        migrations.AlterField(
            model_name='item',
            name='barcode',
            field=models.BigIntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='newmodel',
            name='model',
            field=models.CharField(choices=[('IT', 'Item'), ('SU', 'Supplier'), ('CU', 'Customer'), ('IN', 'inventory'), ('CR', 'credit'), ('PR', 'price'), ('PU', 'purchase'), ('SA', 'sale')], max_length=2),
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
        migrations.AddField(
            model_name='saleitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exchange.item'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.sale'),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exchange.item'),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.purchase'),
        ),
    ]
