# Generated by Django 4.2.11 on 2025-03-20 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0004_purchaseitem_saleitem_remove_purchase_items_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editmodelcontents',
            name='fields_changed',
        ),
        migrations.AddField(
            model_name='fieldchange',
            name='history_instance',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='exchange.editmodelcontents'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='barcode',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
