# Generated by Django 4.2.11 on 2025-03-21 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0006_remove_customer_email_remove_customer_phone_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='title',
            new_name='name',
        ),
    ]
