# Generated by Django 4.2.11 on 2025-03-21 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0007_rename_title_customer_name_rename_title_item_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(blank=True, max_length=45),
        ),
        migrations.AddField(
            model_name='customer',
            name='state',
            field=models.CharField(blank=True, max_length=13),
        ),
        migrations.AddField(
            model_name='customer',
            name='zipcode',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='city',
            field=models.CharField(blank=True, max_length=45),
        ),
        migrations.AddField(
            model_name='supplier',
            name='state',
            field=models.CharField(blank=True, max_length=13),
        ),
        migrations.AddField(
            model_name='supplier',
            name='zipcode',
            field=models.IntegerField(null=True),
        ),
    ]
