# Generated by Django 4.2.11 on 2025-03-21 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0008_customer_city_customer_state_customer_zipcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='zipcode',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='zipcode',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
