# Generated by Django 4.2.11 on 2025-03-21 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0009_alter_customer_zipcode_alter_supplier_zipcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='zipcode',
            field=models.CharField(blank=True, default=85001, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='supplier',
            name='zipcode',
            field=models.CharField(blank=True, default=90034, max_length=10),
            preserve_default=False,
        ),
    ]
