# Generated by Django 4.2.11 on 2025-03-23 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0010_alter_customer_zipcode_alter_supplier_zipcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='barcode',
            field=models.CharField(blank=True, default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='sku',
            field=models.BigIntegerField(),
        ),
    ]
