# Generated by Django 4.2.11 on 2025-03-24 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0012_remove_customer_city_remove_customer_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='sku',
            field=models.IntegerField(),
        ),
    ]
