# Generated by Django 4.2.11 on 2025-03-24 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0014_itemserial_remove_supplier_items_alter_item_sku_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brand_items', to='exchange.itemcategory'),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_items', to='exchange.itemcategory'),
        ),
    ]
