# Generated by Django 4.2.11 on 2025-03-24 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0015_alter_item_item_brand_alter_item_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brand_items', to='exchange.itembrand'),
        ),
    ]
