# Generated by Django 4.2.11 on 2025-03-25 00:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0016_alter_item_item_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('item_brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brand_items', to='exchange.itembrand')),
                ('item_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_items', to='exchange.itemcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItemStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style_type', models.CharField(blank=True, max_length=20)),
                ('style', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ItemUniqueID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id_type', models.CharField(max_length=50)),
                ('unique_id', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('INV', 'In Inventory'), ('SLD', 'Sold'), ('MSN', 'Missing'), ('STL', 'Stolen'), ('NTR', 'Not Tracked')], max_length=3)),
            ],
        ),
        migrations.RemoveField(
            model_name='itemserialstyle',
            name='item_serial',
        ),
        migrations.RemoveField(
            model_name='itemserialstyle',
            name='user',
        ),
        migrations.RemoveField(
            model_name='item',
            name='item_brand',
        ),
        migrations.RemoveField(
            model_name='item',
            name='item_category',
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='sku',
            field=models.CharField(max_length=30),
        ),
        migrations.DeleteModel(
            name='ItemSerial',
        ),
        migrations.DeleteModel(
            name='ItemSerialStyle',
        ),
        migrations.AddField(
            model_name='itemuniqueid',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.item'),
        ),
        migrations.AddField(
            model_name='itemuniqueid',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itemstyle',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.item'),
        ),
        migrations.AddField(
            model_name='itemstyle',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='item',
            name='item_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exchange.itemgroup'),
        ),
    ]
