# Generated by Django 4.2.11 on 2025-03-25 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0017_itemgroup_itemstyle_itemuniqueid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemgroup',
            name='item_brand',
        ),
        migrations.RemoveField(
            model_name='itemgroup',
            name='item_category',
        ),
        migrations.RemoveField(
            model_name='itemgroup',
            name='user',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='sku',
            new_name='SKU',
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('user', 'SKU')},
        ),
        migrations.AddField(
            model_name='item',
            name='item_brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brand_items', to='exchange.itembrand'),
        ),
        migrations.AddField(
            model_name='item',
            name='item_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_items', to='exchange.itemcategory'),
        ),
        migrations.DeleteModel(
            name='ItemStyle',
        ),
        migrations.RemoveField(
            model_name='item',
            name='item_group',
        ),
        migrations.DeleteModel(
            name='ItemGroup',
        ),
    ]
