# Generated by Django 4.2.11 on 2025-03-26 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0018_remove_itemgroup_item_brand_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Credit',
            new_name='Balance',
        ),
        migrations.RenameModel(
            old_name='ItemUniqueID',
            new_name='SerializedItem',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='inventory_restock_warning',
        ),
        migrations.AddField(
            model_name='item',
            name='inventory_restock_warning',
            field=models.IntegerField(default=0),
        ),
    ]
