# Generated by Django 4.2.11 on 2025-03-26 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0019_rename_credit_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='count_serialized',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='serializeditem',
            name='unique_id_type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
