# Generated by Django 4.2.11 on 2025-03-26 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0020_inventory_count_serialized_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serializeditem',
            name='unique_id_type',
            field=models.CharField(max_length=50),
        ),
    ]
