# Generated by Django 4.2.11 on 2025-03-26 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0022_remove_purchase_other_costs_remove_sale_other_costs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='date',
            field=models.DateField(),
        ),
    ]
