# Generated by Django 4.2.11 on 2025-03-26 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0024_alter_purchase_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='serializeditem',
            name='purchase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exchange.purchase'),
        ),
        migrations.AddField(
            model_name='serializeditem',
            name='sale',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exchange.sale'),
        ),
    ]
