# Generated by Django 4.2.11 on 2025-04-01 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0026_nonserializeditemsalelist_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseothercost',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='saleothercost',
            name='currency',
        ),
        migrations.AlterField(
            model_name='nonserializeditempurchaselist',
            name='count',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='nonserializeditemsalelist',
            name='count',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='SaleitemPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exchange.item')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.sale')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PurchaseItemPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exchange.item')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.purchase')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
