# Generated by Django 4.2.11 on 2025-04-01 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0027_remove_purchaseothercost_currency_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseitemprice',
            old_name='cost',
            new_name='unit_cost',
        ),
        migrations.RenameField(
            model_name='saleitemprice',
            old_name='cost',
            new_name='unit_cost',
        ),
    ]
