# Generated by Django 4.2.11 on 2025-04-02 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0028_rename_cost_purchaseitemprice_unit_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonserializeditempurchaselist',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nonserializeditemsalelist',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serializeditem',
            name='unit_purchase_price',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serializeditem',
            name='unit_sold_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
