# Generated by Django 4.2.11 on 2025-04-02 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0029_nonserializeditempurchaselist_unit_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nonserializeditempurchaselist',
            old_name='unit_price',
            new_name='unit_cost',
        ),
        migrations.RenameField(
            model_name='nonserializeditemsalelist',
            old_name='unit_price',
            new_name='unit_cost',
        ),
    ]
