# Generated by Django 4.2.11 on 2025-04-02 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0030_rename_unit_price_nonserializeditempurchaselist_unit_cost_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nonserializeditempurchaselist',
            old_name='unit_cost',
            new_name='unit_price',
        ),
        migrations.RenameField(
            model_name='nonserializeditemsalelist',
            old_name='unit_cost',
            new_name='unit_price',
        ),
    ]
