# Generated by Django 4.2.11 on 2025-04-02 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0031_rename_unit_cost_nonserializeditempurchaselist_unit_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balance',
            old_name='effect_on_date_time',
            new_name='date_time',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='effect_on_date_time',
            new_name='date_time',
        ),
        migrations.RenameField(
            model_name='price',
            old_name='effect_on_date_time',
            new_name='date_time',
        ),
        migrations.RemoveField(
            model_name='balance',
            name='expire_on_date_time',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='expire_on_date_time',
        ),
        migrations.RemoveField(
            model_name='price',
            name='expire_on_date_time',
        ),
    ]
