# Generated by Django 4.2.11 on 2025-04-02 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0032_rename_effect_on_date_time_balance_date_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseitemprice',
            name='item',
        ),
        migrations.RemoveField(
            model_name='purchaseitemprice',
            name='purchase',
        ),
        migrations.RemoveField(
            model_name='purchaseitemprice',
            name='user',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='sale',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='user',
        ),
        migrations.RemoveField(
            model_name='saleitemprice',
            name='item',
        ),
        migrations.RemoveField(
            model_name='saleitemprice',
            name='sale',
        ),
        migrations.RemoveField(
            model_name='saleitemprice',
            name='user',
        ),
        migrations.RenameField(
            model_name='purchaseothercost',
            old_name='charge',
            new_name='cost',
        ),
        migrations.RenameField(
            model_name='saleothercost',
            old_name='charge',
            new_name='cost',
        ),
        migrations.RemoveField(
            model_name='purchaseothercost',
            name='charge_name',
        ),
        migrations.RemoveField(
            model_name='saleothercost',
            name='charge_name',
        ),
        migrations.AddField(
            model_name='purchaseothercost',
            name='Cost_type',
            field=models.CharField(choices=[('SHP', 'Shipping'), ('TAX', 'Tax'), ('OTR', 'Other')], default='TAX', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saleothercost',
            name='Cost_type',
            field=models.CharField(choices=[('SHP', 'Shipping'), ('TAX', 'Tax'), ('OTR', 'Other')], default='TAX', max_length=3),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PurchaseItem',
        ),
        migrations.DeleteModel(
            name='PurchaseItemPrice',
        ),
        migrations.DeleteModel(
            name='SaleItem',
        ),
        migrations.DeleteModel(
            name='SaleitemPrice',
        ),
    ]
