# Generated by Django 4.2.11 on 2025-04-02 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0034_alter_purchaseothercost_cost_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseothercost',
            name='Cost_type',
        ),
        migrations.RemoveField(
            model_name='saleothercost',
            name='Cost_type',
        ),
        migrations.AddField(
            model_name='purchaseothercost',
            name='cost_type',
            field=models.CharField(choices=[('OTR', 'Other'), ('SHP', 'Shipping'), ('TAX', 'Tax')], default='TAX', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saleothercost',
            name='cost_type',
            field=models.CharField(choices=[('OTR', 'Other'), ('SHP', 'Shipping'), ('TAX', 'Tax')], default='TAX', max_length=3),
            preserve_default=False,
        ),
    ]
