# Generated by Django 4.2.11 on 2025-04-02 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0035_remove_purchaseothercost_cost_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseothercost',
            name='cost_type',
            field=models.CharField(choices=[('SHP', 'Shipping'), ('OTR', 'Other'), ('TAX', 'Tax')], max_length=3),
        ),
        migrations.AlterField(
            model_name='saleothercost',
            name='cost_type',
            field=models.CharField(choices=[('SHP', 'Shipping'), ('OTR', 'Other'), ('TAX', 'Tax')], max_length=3),
        ),
    ]
