# Generated by Django 4.2.11 on 2025-04-04 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0036_alter_purchaseothercost_cost_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactinfo',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='editmodelcontents',
            name='user',
        ),
        migrations.RemoveField(
            model_name='fieldchange',
            name='history_instance',
        ),
        migrations.RemoveField(
            model_name='fieldchange',
            name='user',
        ),
        migrations.RemoveField(
            model_name='newmodel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='price',
            name='item',
        ),
        migrations.RemoveField(
            model_name='price',
            name='user',
        ),
        migrations.AlterField(
            model_name='purchaseothercost',
            name='cost_type',
            field=models.CharField(choices=[('OTR', 'Other'), ('TAX', 'Tax'), ('SHP', 'Shipping')], max_length=3),
        ),
        migrations.AlterField(
            model_name='saleothercost',
            name='cost_type',
            field=models.CharField(choices=[('OTR', 'Other'), ('TAX', 'Tax'), ('SHP', 'Shipping')], max_length=3),
        ),
        migrations.AlterField(
            model_name='serializeditem',
            name='status',
            field=models.CharField(choices=[('INV', 'In Inventory'), ('SLD', 'Sold'), ('MSN', 'Missing'), ('STL', 'Stolen'), ('NTR', 'Not Tracked')], default='INV', max_length=3),
        ),
        migrations.DeleteModel(
            name='Balance',
        ),
        migrations.DeleteModel(
            name='ContactInfo',
        ),
        migrations.DeleteModel(
            name='EditModelContents',
        ),
        migrations.DeleteModel(
            name='FieldChange',
        ),
        migrations.DeleteModel(
            name='NewModel',
        ),
        migrations.DeleteModel(
            name='Price',
        ),
    ]
