# Generated by Django 4.2.11 on 2025-04-04 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0037_remove_contactinfo_content_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseothercost',
            name='cost_type',
            field=models.CharField(choices=[('SHP', 'Shipping'), ('OTR', 'Other'), ('TAX', 'Tax')], max_length=3),
        ),
        migrations.AlterField(
            model_name='saleothercost',
            name='cost_type',
            field=models.CharField(choices=[('SHP', 'Shipping'), ('OTR', 'Other'), ('TAX', 'Tax')], max_length=3),
        ),
        migrations.AlterField(
            model_name='serializeditem',
            name='status',
            field=models.CharField(choices=[('INV', 'In Inventory'), ('SLD', 'Sold'), ('MSN', 'Missing'), ('STL', 'Stolen')], default='INV', max_length=3),
        ),
    ]
