# Generated by Django 4.2.11 on 2025-04-04 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0039_alter_purchaseothercost_cost_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseothercost',
            name='cost_type',
            field=models.CharField(choices=[('SHP', 'Shipping'), ('TAX', 'Tax'), ('OTR', 'Other')], max_length=3),
        ),
        migrations.AlterField(
            model_name='saleothercost',
            name='cost_type',
            field=models.CharField(choices=[('SHP', 'Shipping'), ('TAX', 'Tax'), ('OTR', 'Other')], max_length=3),
        ),
    ]
