# Generated by Django 4.2.11 on 2025-04-04 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0042_alter_purchaseothercost_cost_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='count_serialized',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='reason',
        ),
        migrations.AddField(
            model_name='inventory',
            name='active_until',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='purchase_cost',
            field=models.DecimalField(decimal_places=2, default=45, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='purchaseothercost',
            name='cost_type',
            field=models.CharField(choices=[('SHP', 'Shipping'), ('OTR', 'Other'), ('TAX', 'Tax')], max_length=3),
        ),
        migrations.AlterField(
            model_name='saleothercost',
            name='cost_type',
            field=models.CharField(choices=[('SHP', 'Shipping'), ('OTR', 'Other'), ('TAX', 'Tax')], max_length=3),
        ),
    ]
