# Generated by Django 4.2.11 on 2025-04-04 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0043_remove_inventory_count_serialized_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseothercost',
            name='cost_type',
            field=models.CharField(choices=[('OTR', 'Other'), ('TAX', 'Tax'), ('SHP', 'Shipping')], max_length=3),
        ),
        migrations.AlterField(
            model_name='saleothercost',
            name='cost_type',
            field=models.CharField(choices=[('OTR', 'Other'), ('TAX', 'Tax'), ('SHP', 'Shipping')], max_length=3),
        ),
    ]
