# Generated by Django 4.2.11 on 2025-04-04 21:55

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0045_alter_inventory_active_until_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='date',
            field=models.DateField(default=datetime.date(2025, 4, 4)),
        ),
        migrations.AlterField(
            model_name='sale',
            name='date',
            field=models.DateField(default=datetime.date(2025, 4, 4)),
        ),
    ]
