# Generated by Django 4.2.11 on 2025-04-04 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0047_alter_purchase_date_alter_sale_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseothercost',
            name='cost_type',
            field=models.CharField(choices=[('TAX', 'Tax'), ('OTR', 'Other'), ('SHP', 'Shipping')], max_length=3),
        ),
        migrations.AlterField(
            model_name='saleothercost',
            name='cost_type',
            field=models.CharField(choices=[('TAX', 'Tax'), ('OTR', 'Other'), ('SHP', 'Shipping')], max_length=3),
        ),
    ]
