# Generated by Django 4.2.11 on 2025-04-04 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0048_alter_inventory_sale_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
