# Generated by Django 4.2.11 on 2025-04-04 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0049_alter_inventory_sale_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='active_until',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseothercost',
            name='cost_type',
            field=models.CharField(choices=[('OTR', 'Other'), ('TAX', 'Tax'), ('SHP', 'Shipping')], max_length=3),
        ),
        migrations.AlterField(
            model_name='saleothercost',
            name='cost_type',
            field=models.CharField(choices=[('OTR', 'Other'), ('TAX', 'Tax'), ('SHP', 'Shipping')], max_length=3),
        ),
    ]
