# Generated by Django 4.2.11 on 2025-04-04 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0051_alter_inventory_active_until_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='count_sold',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseothercost',
            name='cost_type',
            field=models.CharField(choices=[('SHP', 'Shipping'), ('OTR', 'Other'), ('TAX', 'Tax')], max_length=3),
        ),
        migrations.AlterField(
            model_name='saleothercost',
            name='cost_type',
            field=models.CharField(choices=[('SHP', 'Shipping'), ('OTR', 'Other'), ('TAX', 'Tax')], max_length=3),
        ),
    ]
