# Generated by Django 4.2.11 on 2025-04-06 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0052_inventory_count_sold_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseothercost',
            name='cost_type',
            field=models.CharField(choices=[('TAX', 'Tax'), ('OTR', 'Other'), ('SHP', 'Shipping')], max_length=3),
        ),
        migrations.AlterField(
            model_name='saleothercost',
            name='cost_type',
            field=models.CharField(choices=[('TAX', 'Tax'), ('OTR', 'Other'), ('SHP', 'Shipping')], max_length=3),
        ),
    ]
