# Generated by Django 4.2.11 on 2025-04-09 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0054_alter_purchaseothercost_cost_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serializeditem',
            name='sale',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exchange.sale'),
        ),
        migrations.AlterField(
            model_name='serializeditem',
            name='unit_sold_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
    ]
