# Generated by Django 4.2.11 on 2025-04-10 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0055_alter_serializeditem_sale_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='active_until',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseothercost',
            name='cost_type',
            field=models.CharField(choices=[('OTR', 'Other'), ('TAX', 'Tax'), ('SHP', 'Shipping')], max_length=3),
        ),
        migrations.AlterField(
            model_name='saleothercost',
            name='cost_type',
            field=models.CharField(choices=[('OTR', 'Other'), ('TAX', 'Tax'), ('SHP', 'Shipping')], max_length=3),
        ),
    ]
