# Generated by Django 4.2.11 on 2025-04-10 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0056_alter_inventory_active_until_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='active_until',
            field=models.DateTimeField(null=True),
        ),
    ]
