# Generated by Django 4.2.11 on 2025-04-16 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0057_alter_inventory_active_until'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nonserializeditempurchaselist',
            old_name='unit_price',
            new_name='unit_purchase_price',
        ),
        migrations.RenameField(
            model_name='nonserializeditemsalelist',
            old_name='unit_price',
            new_name='unit_purchase_price',
        ),
        migrations.AddField(
            model_name='nonserializeditempurchaselist',
            name='unit_sale_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='nonserializeditemsalelist',
            name='unit_sale_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseothercost',
            name='cost_type',
            field=models.CharField(choices=[('SHP', 'Shipping'), ('TAX', 'Tax'), ('OTR', 'Other')], max_length=3),
        ),
        migrations.AlterField(
            model_name='saleothercost',
            name='cost_type',
            field=models.CharField(choices=[('SHP', 'Shipping'), ('TAX', 'Tax'), ('OTR', 'Other')], max_length=3),
        ),
    ]
