# Generated by Django 4.2.11 on 2025-04-16 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0058_rename_unit_price_nonserializeditempurchaselist_unit_purchase_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nonserializeditempurchaselist',
            old_name='unit_purchase_price',
            new_name='unit_price',
        ),
        migrations.RenameField(
            model_name='nonserializeditemsalelist',
            old_name='unit_purchase_price',
            new_name='unit_price',
        ),
        migrations.RemoveField(
            model_name='nonserializeditempurchaselist',
            name='unit_sale_price',
        ),
        migrations.RemoveField(
            model_name='nonserializeditemsalelist',
            name='unit_sale_price',
        ),
        migrations.AddField(
            model_name='nonserializeditempurchaselist',
            name='inventories',
            field=models.ManyToManyField(to='exchange.inventory'),
        ),
        migrations.AddField(
            model_name='nonserializeditemsalelist',
            name='inventories',
            field=models.ManyToManyField(to='exchange.inventory'),
        ),
        migrations.AlterField(
            model_name='purchaseothercost',
            name='cost_type',
            field=models.CharField(choices=[('OTR', 'Other'), ('TAX', 'Tax'), ('SHP', 'Shipping')], max_length=3),
        ),
        migrations.AlterField(
            model_name='saleothercost',
            name='cost_type',
            field=models.CharField(choices=[('OTR', 'Other'), ('TAX', 'Tax'), ('SHP', 'Shipping')], max_length=3),
        ),
    ]
