# Generated by Django 4.2.11 on 2025-04-16 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0059_rename_unit_purchase_price_nonserializeditempurchaselist_unit_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonserializeditempurchaselist',
            name='inventories',
            field=models.ManyToManyField(related_name='purchase_lists', to='exchange.inventory'),
        ),
        migrations.AlterField(
            model_name='nonserializeditemsalelist',
            name='inventories',
            field=models.ManyToManyField(related_name='sale_lists', to='exchange.inventory'),
        ),
        migrations.AlterField(
            model_name='purchaseothercost',
            name='cost_type',
            field=models.CharField(choices=[('TAX', 'Tax'), ('OTR', 'Other'), ('SHP', 'Shipping')], max_length=3),
        ),
        migrations.AlterField(
            model_name='saleothercost',
            name='cost_type',
            field=models.CharField(choices=[('TAX', 'Tax'), ('OTR', 'Other'), ('SHP', 'Shipping')], max_length=3),
        ),
    ]
