# Generated by Django 4.2.11 on 2025-04-17 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0061_alter_purchaseothercost_cost_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='nsi_purchase_l',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exchange.nonserializeditempurchaselist'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='nsi_sale_l',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exchange.nonserializeditemsalelist'),
        ),
        migrations.AlterField(
            model_name='nonserializeditempurchaselist',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ns_item_list', to='exchange.purchase'),
        ),
        migrations.AlterField(
            model_name='nonserializeditemsalelist',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ns_item_list', to='exchange.sale'),
        ),
        migrations.AlterField(
            model_name='purchaseothercost',
            name='cost_type',
            field=models.CharField(choices=[('SHP', 'Shipping'), ('OTR', 'Other'), ('TAX', 'Tax')], max_length=3),
        ),
        migrations.AlterField(
            model_name='saleothercost',
            name='cost_type',
            field=models.CharField(choices=[('SHP', 'Shipping'), ('OTR', 'Other'), ('TAX', 'Tax')], max_length=3),
        ),
    ]
