# Generated by Django 4.2.11 on 2025-04-17 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0062_inventory_nsi_purchase_l_inventory_nsi_sale_l_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nonserializeditempurchaselist',
            name='inventories',
        ),
        migrations.RemoveField(
            model_name='nonserializeditemsalelist',
            name='inventories',
        ),
        migrations.AlterField(
            model_name='inventory',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
