# Generated by Django 4.2.11 on 2025-04-17 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0063_remove_nonserializeditempurchaselist_inventories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='nsi_sale_l',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exchange.nonserializeditemsalelist'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseothercost',
            name='cost_type',
            field=models.CharField(choices=[('TAX', 'Tax'), ('SHP', 'Shipping'), ('OTR', 'Other')], max_length=3),
        ),
        migrations.AlterField(
            model_name='saleothercost',
            name='cost_type',
            field=models.CharField(choices=[('TAX', 'Tax'), ('SHP', 'Shipping'), ('OTR', 'Other')], max_length=3),
        ),
    ]
