# Generated by Django 4.2.11 on 2025-04-17 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0064_alter_inventory_nsi_sale_l_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='active_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
