# Generated by Django 4.2.11 on 2025-04-18 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0065_alter_inventory_active_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='nsi_purchase_l',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='exchange.nonserializeditempurchaselist'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='nsi_sale_l',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='exchange.nonserializeditemsalelist'),
        ),
        migrations.AlterField(
            model_name='purchaseothercost',
            name='cost_type',
            field=models.CharField(choices=[('OTR', 'Other'), ('SHP', 'Shipping'), ('TAX', 'Tax')], max_length=3),
        ),
        migrations.AlterField(
            model_name='saleothercost',
            name='cost_type',
            field=models.CharField(choices=[('OTR', 'Other'), ('SHP', 'Shipping'), ('TAX', 'Tax')], max_length=3),
        ),
    ]
