# Generated by Django 4.2.11 on 2025-04-18 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0066_alter_inventory_nsi_purchase_l_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory', to='exchange.item'),
        ),
        migrations.AlterField(
            model_name='purchaseothercost',
            name='cost_type',
            field=models.CharField(choices=[('OTR', 'Other Cost'), ('SHP', 'Shipping'), ('TAX', 'Tax')], max_length=3),
        ),
        migrations.AlterField(
            model_name='purchaseothercost',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_cost', to='exchange.purchase'),
        ),
        migrations.AlterField(
            model_name='saleothercost',
            name='cost_type',
            field=models.CharField(choices=[('OTR', 'Other Cost'), ('SHP', 'Shipping'), ('TAX', 'Tax')], max_length=3),
        ),
        migrations.AlterField(
            model_name='saleothercost',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_cost', to='exchange.sale'),
        ),
    ]
