# Generated by Django 4.2.11 on 2025-05-11 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0068_alter_customer_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseothercost',
            name='cost_type',
            field=models.CharField(choices=[('OTR', 'Other Cost'), ('SHP', 'Shipping'), ('TAX', 'Tax')], max_length=3),
        ),
        migrations.AlterField(
            model_name='saleothercost',
            name='cost_type',
            field=models.CharField(choices=[('OTR', 'Other Cost'), ('SHP', 'Shipping'), ('TAX', 'Tax')], max_length=3),
        ),
    ]
