# Generated by Django 4.2.11 on 2025-01-17 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auctionlisting_comment_bid_auctionlisting_bidders_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionlisting',
            name='sellers',
        ),
    ]
