# Generated by Django 4.2.11 on 2025-01-27 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_watchlist_auction_id_watchlist_user_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='watchlist',
            unique_together={('user_id', 'auction_id')},
        ),
    ]
