# Generated by Django 4.2.11 on 2025-01-29 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auctionlisting_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='category',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='image_url',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
